spring:
   application:
      name: demoservice
server:
   port: 9080

---
spring:
   profiles: dev
   application:
      name: demoservice
server:
   port: 9070

---
spring: 
   profiles: prod
   application:
      name: demoservice
server: 
   port: 4431